# Generated by Django 4.2.3 on 2023-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
